# Generated by Django 4.1.5 on 2023-02-17 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_imagemodel_created_at_imagemodel_uploaded_by"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="leader_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="about.clubmodel",
            ),
        ),
    ]
