# Generated by Django 4.1.5 on 2023-02-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="leader",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
