# Generated by Django 4.1.5 on 2023-02-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0008_alter_imagemodel_image"),
        ("account", "0002_user_leader"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="leader",),
        migrations.AddField(
            model_name="user",
            name="leader_of",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="about.clubmodel",
            ),
        ),
    ]
