# Generated by Django 4.1.5 on 2023-03-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0006_clubmodel_members"),
        ("account", "0002_alter_user_leader_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="member_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_of+",
                to="about.clubmodel",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="leader_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leader_of+",
                to="about.clubmodel",
            ),
        ),
    ]
