# Generated by Django 4.1.5 on 2024-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_member_of_alter_user_leader_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
