# Generated by Django 4.1.5 on 2023-02-10 02:33

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('club', models.CharField(max_length=10)),
                ('section', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder)),
            ],
        ),
    ]
