# Generated by Django 4.1.5 on 2023-03-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0004_formmodel_first_result_formmodel_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formmodel",
            name="time",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
