# Generated by Django 4.1.5 on 2024-02-11 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_remove_formmodel_time_timemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='time_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timemodel',
            name='current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timemodel',
            name='number',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='time_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
