# Generated by Django 4.1.5 on 2024-02-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_remove_clubmodel_times_clubmodel_end'),
        ('form', '0008_formmodel_second_result_alter_formmodel_first_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timemodel',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_club+', to='about.clubmodel'),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='first_result',
            field=models.CharField(choices=[('W', 'WAIT'), ('P', 'PASS'), ('F', 'FAIL'), ('A', 'ADDITIONAL_PASS'), ('G', 'GIVE_UP')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='second_result',
            field=models.CharField(choices=[('W', 'WAIT'), ('P', 'PASS'), ('F', 'FAIL'), ('A', 'ADDITIONAL_PASS'), ('G', 'GIVE_UP')], default='W', max_length=1),
        ),
    ]
