# Generated by Django 5.0.3 on 2024-03-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_alter_formmodel_first_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='additional_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
