# Generated by Django 5.0.3 on 2024-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_formmodel_additional_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='additional_rank',
            field=models.IntegerField(default=0),
        ),
    ]
