# Generated by Django 4.1.5 on 2023-02-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club", models.CharField(max_length=10)),
                ("image", models.FileField(null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="ClubModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_start", models.DateTimeField(auto_now=True)),
                ("form_end", models.DateTimeField(auto_now=True)),
                ("index_banner_description", models.TextField()),
                (
                    "about_text",
                    models.TextField(default="# 동아리 소개 준비중\n동아리에서 아직 내용을 준비하는 중이에요."),
                ),
                (
                    "about_background",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_background+",
                        to="about.imagemodel",
                    ),
                ),
                (
                    "about_images",
                    models.ManyToManyField(
                        related_name="about_images+", to="about.imagemodel"
                    ),
                ),
                (
                    "index_banner_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_banner_image+",
                        to="about.imagemodel",
                    ),
                ),
            ],
        ),
    ]
