# Generated by Django 4.1.5 on 2023-02-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.FileField(null=True, upload_to="media/"),
        ),
    ]
