# Generated by Django 4.1.5 on 2023-02-16 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imagemodel",
            name="uploaded_by",
            field=models.IntegerField(default=10323),
            preserve_default=False,
        ),
    ]
