# Generated by Django 4.1.5 on 2023-02-13 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_alter_imagemodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmodel",
            name="about_background",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about_background+",
                to="about.imagemodel",
            ),
        ),
        migrations.AlterField(
            model_name="clubmodel",
            name="index_banner_description",
            field=models.TextField(default="동아리 소개 준비중"),
        ),
        migrations.AlterField(
            model_name="clubmodel",
            name="index_banner_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="index_banner_image+",
                to="about.imagemodel",
            ),
        ),
    ]
