# Generated by Django 4.1.5 on 2023-02-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_imagemodel_created_at_imagemodel_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmodel",
            name="kakao_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
