# Generated by Django 4.1.5 on 2023-02-13 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_alter_clubmodel_about_background_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmodel",
            name="about_background",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="about_background+",
                to="about.imagemodel",
            ),
        ),
        migrations.AlterField(
            model_name="clubmodel",
            name="index_banner_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="index_banner_image+",
                to="about.imagemodel",
            ),
        ),
    ]
