# Generated by Django 4.1.5 on 2023-02-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_clubmodel_kakao_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmodel",
            name="kakao_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
