# Generated by Django 4.1.5 on 2023-02-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_alter_clubmodel_about_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmodel",
            name="code",
            field=models.CharField(default="test_club", max_length=10),
        ),
        migrations.AddField(
            model_name="clubmodel",
            name="name",
            field=models.CharField(default="테스트_동아리", max_length=100),
        ),
    ]
