# Generated by Django 4.1.5 on 2023-02-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0005_clubmodel_code_clubmodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmodel",
            name="logo_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logo_image+",
                to="about.imagemodel",
            ),
        ),
        migrations.AlterField(
            model_name="clubmodel",
            name="about_background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="about_background+",
                to="about.imagemodel",
            ),
        ),
        migrations.AlterField(
            model_name="clubmodel",
            name="about_images",
            field=models.ManyToManyField(
                blank=True, related_name="about_images+", to="about.imagemodel"
            ),
        ),
        migrations.AlterField(
            model_name="clubmodel",
            name="index_banner_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="index_banner_image+",
                to="about.imagemodel",
            ),
        ),
    ]
