# Generated by Django 4.1.5 on 2023-02-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0006_clubmodel_logo_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmodel",
            name="code",
            field=models.CharField(default="test_club", max_length=10, unique=True),
        ),
    ]
