# Generated by Django 4.1.5 on 2023-03-04 02:54

import datetime
from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0006_clubmodel_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmodel",
            name="time_data",
            field=models.JSONField(
                decoder=json.decoder.JSONDecoder,
                default=list,
                encoder=json.encoder.JSONEncoder,
            ),
        ),
        migrations.AddField(
            model_name="clubmodel",
            name="time_end",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="clubmodel",
            name="time_start",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="clubmodel",
            name="time_use",
            field=models.BooleanField(default=False),
        ),
    ]
