# Generated by Django 4.1.5 on 2023-03-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0007_clubmodel_time_data_clubmodel_time_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="clubmodel", name="time_end",),
        migrations.RemoveField(model_name="clubmodel", name="time_start",),
    ]
