# Generated by Django 4.1.5 on 2023-02-14 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0008_alter_imagemodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmodel",
            name="form_end",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="clubmodel",
            name="form_start",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
