# Generated by Django 4.1.5 on 2023-03-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0008_remove_clubmodel_time_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmodel",
            name="time_start",
            field=models.DateTimeField(default="2024-03-02T00:00:00+09:00"),
        ),
    ]
