# Generated by Django 4.1.5 on 2023-02-14 16:55

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0009_alter_clubmodel_form_end_alter_clubmodel_form_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmodel",
            name="form_data",
            field=models.JSONField(
                decoder=json.decoder.JSONDecoder,
                default={
                    "description": "아직 동아리에서 지원서 양식을 제공하지 않았습니다.",
                    "items": [],
                    "title": "지원서 정보 없음",
                },
                encoder=json.encoder.JSONEncoder,
            ),
        ),
    ]
