# Generated by Django 4.1.5 on 2023-03-07 18:14
from django.apps import apps
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0009_clubmodel_time_start"),
    ]

    operations = [
    ]
