# Generated by Django 4.1.5 on 2023-03-07 18:14
from django.apps import apps
from django.db import migrations


def time_data_sort(a, b):
    ClubModel = apps.get_model('about', 'ClubModel')
    clubs = ClubModel.objects.all()

    for club in clubs:
        time_data = club.time_data
        if time_data:
            time_data.sort(key=lambda x: (x['date'], x['start'], x['end']))
            for time in time_data:
                time['current'] = 0
            club.time_data = time_data
            club.save()


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0009_clubmodel_time_start"),
    ]

    operations = [
        migrations.RunPython(time_data_sort)
    ]
