# Generated by Django 4.1.5 on 2023-02-14 16:57

import about.models
from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0010_clubmodel_form_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmodel",
            name="form_data",
            field=models.JSONField(
                decoder=json.decoder.JSONDecoder,
                default=about.models.form_data_default,
                encoder=json.encoder.JSONEncoder,
            ),
        ),
    ]
