# Generated by Django 4.1.5 on 2024-02-11 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_rename_time_data_clubmodel_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='form_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clubmodel',
            name='form_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clubmodel',
            name='time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
