# Generated by Django 5.0.2 on 2024-02-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_remove_clubmodel_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmodel',
            name='times',
        ),
    ]
