# Generated by Django 4.1.5 on 2024-02-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_remove_clubmodel_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmodel',
            name='times',
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
