# Generated by Django 4.1.5 on 2023-02-13 05:10

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "circle",
                    models.JSONField(
                        decoder=json.decoder.JSONDecoder,
                        encoder=json.encoder.JSONEncoder,
                    ),
                ),
                (
                    "interview_time",
                    models.JSONField(
                        decoder=json.decoder.JSONDecoder,
                        encoder=json.encoder.JSONEncoder,
                    ),
                ),
            ],
        ),
    ]
