# Generated by Django 4.1.5 on 2024-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(default='PREPARE', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='MyPageModel',
        ),
    ]
