# Generated by Django 4.1.5 on 2024-02-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_statusmodel_delete_mypagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusmodel',
            old_name='current_status',
            new_name='current',
        ),
    ]
